carpool/carpool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('users/', include('users.urls')),
    path('', include('rides.urls')),
    path('admin/', admin.site.urls),
]

carpool/rides/urls.py
from django.urls import path
from . import views

app_name = 'rides'
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:ride_id>/", views.detail, name="detail"),
    path("add_ride", views.add_ride, name="add_ride"),
    path("request", views.request_ride, name="request_ride"),
    path("request/<int:request_id>", views.request_detail, name="request_detail"),
    path("request_cancel/<int:request_id>", views.request_cancel, name="request_cancel"),
    path("contact", views.contact, name="contact"),
    path("success", views.success, name="success"),
]

carpool/users/urls.py
from . import views
from  django.urls import path

app_name = "users"
urlpatterns = [
    path("", views.login_page, name="login"),
    path("logout", views.logout_view, name="logout"), 
    path("myrides",views.my_rides, name="my_rides"),
]

carpool/rides/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User

# Create your models here.
class Ride(models.Model):
    origin = models.CharField(max_length=64)
    destination = models.CharField(max_length=64)
    date = models.DateField()
    time = models.TimeField()
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    seats=models.IntegerField(default=1)
    pickupDirections = models.CharField(max_length=200, default='')

    def __str__(self):
        return f"{self.origin}-{self.destination}:{self.date} at {self.time}"

class Passenger(models.Model):
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    rides = models.ManyToManyField(Ride, blank=True, related_name="passengers")
    
    def __str__(self):
        return f"{self.name}"

class RequestRide(models.Model):
    origin = models.CharField(max_length=64)
    destination = models.CharField(max_length=64)
    date = models.DateField()
    time = models.CharField(max_length=200)
    name = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Requested from {self.origin} to {self.destination} for {self.date} at {self.time}"

carpool/rides/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django import forms


class ContactForm(forms.Form):
    name = forms.EmailField(label='Email', max_length=60)
    message = forms.CharField(widget=forms.Textarea, label="How can we help you?")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            'name',
            'message',
            Submit('submit','Contact', css_class='btn-primary')
        )

carpool/rides/views.py
# from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.http import HttpRequest, Http404, HttpResponseRedirect, HttpResponse
from django.urls import reverse
from .models import Ride, Passenger, RequestRide
from django.utils import timezone
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
import datetime
from datetime import timedelta
from .forms import ContactForm

def bookRide(request, passenger, ride):
    #add the passenger to that ride
    passenger.rides.add(ride)
    #send confimation email to both riders and host
    send_mail(
        'Ride Confirmed',
        f'Your ride has been booked. The host is {ride.name.first_name} {ride.name.last_name}. Email: {ride.name.email}',
        'ride2luther@gmail.com',
        [f'{passenger.name.email}'],
        fail_silently=False,
    )
    send_mail(
        'Passenger Joined',
        f'A new passenger has joined your ride. Name: {passenger.name.first_name} {passenger.name.last_name}. Email: {passenger.name.email}',
        'ride2luther@gmail.com',
        [f'{ride.name.email}'],
        fail_silently=False,
    )
    
    return render(request, "rides/success.html" , {"host":ride.name.username, "ride":ride})

def index(request):
    # rides = Ride.objects.filter(date__gte==timezone.now())
    rides = Ride.objects.all()
    rides = rides.filter(date__gte=timezone.now())
    rides = rides.order_by('date')

    # order the rides by date ascending order


    requested_rides = RequestRide.objects.all()
    requested_rides = requested_rides.filter(date__gte=timezone.now())
    requested_rides = requested_rides.order_by('date')

    # order the rides by date ascending order


    # filter rides with seats_remaining > 0
    context = {
        "rides": rides,
        "now": timezone.now(),
        "loggedIn" : request.user.is_authenticated,
        "requested_rides": requested_rides,
    }
    return render(request, "rides/index.html", context)

@login_required(login_url='/users/')
def detail(request, ride_id):
    ride = Ride.objects.get(pk=ride_id)
    if request.method == 'POST':
        if request.user.username == ride.name.username:
            pickupDescription = request.POST.get('pickupDirections')
            ride.pickupDirections = pickupDescription
            ride.save()
            return redirect(f"/{ride_id}")
        else:
            seats_remaning = ride.seats - len(ride.passengers.all())
            # if the ride isn't fully booked already
            if seats_remaning >= 1:

                # get the authenticated user's username
                user = request.user
                username = user.username
                #check if the person giving ride is not the user (can't book a ride for himself) 
                if ride.name.username != username:
                    
                    # if that user is not yet a Passenger object, create one
                    passengerName = Passenger.objects.filter(name=user)
                    
                    if not passengerName:
                        #create a passenger with that username, book ride for the user
                        passenger = Passenger(name=user)
                        passenger.save()
                        
                        return bookRide(request, passenger, ride)
                    
                    else:
                        passenger = passengerName[0]
                        #check if the user is already not on the ride 
                        if ride not in passenger.rides.all():
                            #book ride for that user
                            return bookRide(request, passenger, ride)

                        else:
                            message = "You cannot book a ride twice"
                            return render(request, "rides/error.html", {"message":message})

                else:
                    message = "You cannot book a ride for yourself"
                    #redirect to error page
                    return render(request, "rides/error.html", {"message":message}) 

            else:
                #redirect with not success message
                message = "This ride is fully booked"
                return render(request, "rides/error.html", {"message":message}) 
    else:
        passengers = []
        for passenger in ride.passengers.all():
            passengers.append(passenger.name)
        
        context = {
            "ride": ride,
            "seats_remaining":ride.seats - len(ride.passengers.all()),
            "passengers": passengers,
            "user": request.user,
        }
        return render(request, "rides/detail.html", context)


def rideValid(origin, destination, date, seats):
    message = ''
    #check some error conditions 
    #error if origin and destination are same
    if origin == destination:
        message = "Origin and Destination cannot be same!"
    # error if trying to book for past date
        
    elif date < timezone.now().date():
        message = "You cannot add a ride for the past date"
    # error if booking for beyond 90 days
    elif date >  timezone.now().date() + timedelta(days=90):
        message = "New ride must be within 90 days relative to today."
    # error if number of seats is less than 1
    elif int(seats) <= 0:
        message = "Number of seats must be greater than 0"
    return message

@login_required(login_url='/users/')
def add_ride(request):
    if request.method == 'POST':
        origin = request.POST.get('origin')
        destination = request.POST.get('destination')
        date = request.POST.get('date')
        time = request.POST.get('time')
        seats = request.POST.get('seats')
        name = request.user
        pickupDirections = request.POST.get('pickupDirections')
        message = ''
        date = datetime.datetime.strptime(date, "%Y-%m-%d").date()
        # check the lenght of fileds?
        #call the rideValid for check the validity of ride
        message = rideValid(origin, destination, date, seats)

        #if message is not '', it implies some error was triggered
        if message != '':
            return render(request, "rides/add_ride.html", {"message":message})
        else:
            # some input could be bad. so try to create a ride with the given data
            # display error if it is not possible
            try:
                newRide = Ride(origin=origin, destination=destination, date=date, time=time, seats=seats, name=name, pickupDirections=pickupDirections)
            except:
                return render(request, "rides/add_ride.html", {"message":"Invalid Entry. Please Try Again"})
            newRide.save()
            rideId = newRide.id
            return redirect(f"/{rideId}")
    else:
        return render(request, 'rides/add_ride.html')

def success(request):
    message = "Action performed successfully."
    return render(request, "rides/success.html", {"message":message})


@login_required(login_url='/users')
def request_cancel(request, request_id):
    if request.method == 'POST':
        #get the ride with request_id primary key
        ride_requested = RequestRide.objects.get(pk=request_id)
        #deleted the ride
        ride_requested.delete()
        # success message
        message = "The ride you requested has been successfully deleted."
        # render the success page
        return redirect("/success")
        # return render(request, "rides/success.html", {"message":message})

@login_required(login_url='/users')
def request_detail(request, request_id):
    try:
        request_ride = RequestRide.objects.get(pk=request_id)
    except:
        #no such requested ride exists
        return render(request, "rides/error.html", {"message":"No such requested ride."})        
    # POST method if someone wants to accept to give that ride.
    if request.method == "POST":
        # if someone wants to host that ride
        #get the description of the requested ride
        origin = request_ride.origin
        destination = request_ride.destination
        date = request_ride.date
        time = request.POST.get('time')
        seats = request.POST.get('seats')
        pickupDirections = request.POST.get('pickupDirections')
        # the host of the ride will be user providing the ride
        name = request.user 
        #check the validity of the ride
        message = rideValid(origin, destination, date, seats)
        # if no errors exist, try creating the ride
        if message == '':
            try:
                newRide = Ride(origin=origin, destination=destination, date=date, time=time, seats=seats, name=name, pickupDirections=pickupDirections)
            except:
                # return the error page
                return render(request, "rides/error.html", {"message":"Invalid Entry. Please Try Again Later"})            
            # delete that ride in the RequestRide table
            request_ride.delete()
            # add the ride to the Passenger who requested the ride
            newRide.save()
            passenger_user = request_ride.name
            #get the passenger with that username, if exists
            #if not create the passenger 
            try:
                passenger = Passenger.objects.filter(name=passenger_user)[0]
            except:
                passenger = Passenger(name=passenger_user)
                passenger.save()
            return bookRide(request, passenger, newRide)
        else:
            # render the error page displaying the error found by rideValid function.
            return render(request, "rides/error.html", {"message":message})
    else:
        # if the request isn't POST(i.e GET)
        #display the details for the requested ride.
        return render(request, "rides/request_detail.html", {"ride": request_ride, "user":request.user})

@login_required(login_url='/users/')

carpool/rides/templates/rides/add_ride.html
{% extends "rides/base.html" %}
{% block titile %} Add a Ride {% endblock %}
{% block content %} 
{% if message %}
<div>
    <h2>{{message}}</h2>
    <br>
</div>
{% endif %}




<form action="{% url 'rides:add_ride' %}" method="POST">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="origin">From</label>
        <input type="text" class="form-control" name="origin" placeholder="Sitapaila" required>
      </div>
      <div class="form-group col-md-6">
        <label for="destination">To</label>
        <input type="text" class="form-control" name="destination" placeholder="Devghat" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="Date">Date</label>
        <input type="date" class="form-control" id="date" name="date" required>
      </div>
      <div class="form-group col-md-6">
        <label for="time">Time</label>
        <input type="time" class="form-control" value="15:15" name="time" required>
    </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-6">
          <label for="seats">Seats</label>
          <input type="number" class="form-control" value="1" name="seats" required>
        </div>
        <div class="form-group col-md-6">
          <label for="pickupDirections">Pickup Point</label>
          <input type="text" name="pickupDirections" class="form-control" placeholder="Pashupatinath North Door" required>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Add My Ride</button>
  </form>
<br>
{% endblock %}

{% block account %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
{% endblock %}

carpool/rides/templates/rides/base.html
{% load static %}
<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="HandheldFriendly" content="true">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'rides/style.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Carme|Cinzel+Decorative&display=swap" rel="stylesheet">
        <script src="{% static 'rides/javas.js' %}"></script>
        <title> {%block title %}{% endblock %}</title>
    </head>
    <body>
      <div id="header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
          <div class="container">
              <a class="navbar-brand" href="{% url 'rides:index' %}"><h3 class="header-font">Luther Rideshare</h3></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'rides:index' %}">Available/Requested<span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'rides:request_ride' %}">Request Ride</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link"href="{% url 'rides:add_ride' %}">Add</a>
                  </li>
                </ul>
              </div>
          </div>
      </nav>
      </div>
          
        <div id="allBody" class="container">
            {% block content %}{% endblock %}
        </div>
  <div id="footer">
    <footer class="page-footer font-small indigo">
      <div class="container text-center text-md-left">
        <div class="row">
          <div class="col-md-4 mx-auto">
            <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Account</h5>
            <ul class="list-unstyled">
                {% block account %} {% endblock %}
            </ul>
          </div>
          <hr class="clearfix w-100 d-md-none">
          <!-- Grid column -->
          <div class="col-md-4 mx-auto">
    
            <!-- Links -->
            <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Info</h5>
    
            <ul class="list-unstyled">
              <li>
                <a href="https://www.luther.edu/sustainability/" target="_blank">About</a>
              </li>
              <li>
                  <a href="{% url 'rides:contact' %}" >Contact us</a>
                </li>
            </ul>
          </div>
          <!-- Grid column -->
    
          <hr class="clearfix w-100 d-md-none">
    
          <!-- Grid column -->
          <div class="col-md-4 mx-auto">
    
            <!-- Links -->
            <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Policies</h5>
    
            <ul class="list-unstyled">
              <li>
                <a href="#!">Terms of use</a>
              </li>
            </ul>
    
          </div>
          <!-- Grid column -->
    
        </div>
        <!-- Grid row -->
    
      </div>
    
    </footer>
  </div>
  
    </body>
</html>

carpool/rides/templates/rides/contact.html
{% extends 'rides/base.html' %}
{% load crispy_forms_tags %}
{% block title %} Contact us {% endblock %}
{% block content %}
        {% crispy form form.helper %}   
{% endblock %}
{% block account %}
    {% if loggedIn %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
    {% else %}
    <li>
        <a href="{% url 'users:login' %}">Login</a>
    </li> 
    {% endif %}
{% endblock %}

carpool/rides/templates/rides/detail.html
{% extends 'rides/base.html' %}
{% block title %} {{ ride.id }} {% endblock %}
{% block content %}
    <h3>Details - RSLCA{{ride.id}}</h3>
    <div class="table-container">
    <table class="table table-hover">
        <tr>
            <th>Origin</th>
            <th>Destination</th>
            <th>Date</th>
            <th>Time</th>
            <th>Seats left</th>
            <th>Pickup point</th>
        </tr>
        <tr>
            <td>{{ride.origin}}</td>
            <td>{{ride.destination}}</td>
            <td>{{ride.date}}</td>
            <td>{{ride.time}}</td>
            <td>{{seats_remaining}}</td>
            <td>{{ride.pickupDirections}}</td>
        </tr>
    </table>
</div>
   
    {% if user == ride.name %}
        <div>You: HOST</div>
        <br>
        {% if passengers %}
        <h5>Passengers</h5>
        <ol>
            {% for passenger in passengers %}
            <li>{{passenger}} - {{passenger.first_name}} {{passenger.last_name}}</li>
            {% endfor %}
        </ol>
        <br>
        {% else %}
        <div>No passengers yet</div>
        {% endif %}
        <br>
        <div>
            <form action="{% url 'rides:detail' ride.id %}" method="post">
                {% csrf_token %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="pickupDirections">Update Pickup Point</label>
                        <input type="text" name="pickupDirections" class="form-control" value="{{ride.pickupDirections}}">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Update Pickup Point</button>
            </form>
        </div>
    {% elif user in passengers %}
        <div>You: Passenger</div>
        <div>HOST: {{ride.name}} - {{ride.name.first_name}} {{ride.name.last_name}}</div>
    {% else %}
        <form action="{% url 'rides:detail' ride.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Join this Ride</button>
        </form>
    {% endif %}
{% endblock %}
{% block account %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
{% endblock %}

carpool/rides/templates/rides/error.html
{% extends 'rides/base.html' %}
{% block title %} Error {% endblock %}
{% block content %}
<div>Error</div>
<div>{{message}}</div>
{% endblock %}
{% block account %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
{% endblock %}

carpool/rides/templates/rides/index.html
{% extends "rides/base.html" %}
{% block title %} Home {% endblock %}
{% block content %}
{% if message %}
<div>{{message}}</div>
{% endif %}
<h3>Upcoming Rides</h3>
{% if rides %}
    <div class="table-responsive mt-3">
    <table class="table table-hover">
        <tr>
            <th>Booking ID</th>
            <th>From</th>
            <th>To</th>
            <th>Date</th>
            <th>Time</th>
            <th>Host</th>
        </tr>
        {% for ride in rides %}
            <tr>
                <td><a href="{% url 'rides:detail' ride.id %}">RSLCA{{ride.id}}</a></td>
                <td>{{ride.origin}}</td>
                <td>{{ride.destination}}</td>
                <td>{{ride.date}}</td>
                <td>{{ride.time}}</td>
                <td>{% if loggedIn %}
                    {{ride.name}}
                    {% else %}
                    <a href="{% url 'users:login' %}">Login To View</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<p>No rides</p>
{% endif %}
<br>
<br>
<h3>Requested Rides</h3>
{% if requested_rides %}
<div class="table-responsive mt-3">
    <table class="table table-hover">
        <tr>
            <th>Request</th>
            <th>From</th>
            <th>To</th>
            <th>Date</th>
            <th>Time</th>
            <th>Requested by</th>
        </tr>
        {% for ride in requested_rides %}
            <tr>
                <td><a href="{% url 'rides:request_detail' ride.id %}">Give Ride</a></td>
                <td>{{ride.origin}}</td>
                <td>{{ride.destination}}</td>
                <td>{{ride.date}}</td>
                <td>{{ride.time}}</td>
                <td>{% if loggedIn %}
                    {{ride.name}}
                    {% else %}
                    <a href="{% url 'users:login' %}">Login To View</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<p>No rides</p>
{% endif %}

<br><br>

{% endblock %}

{% block account %}
    {% if loggedIn %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
    {% else %}
    <li>
        <a href="{% url 'users:login' %}">Login</a>
    </li> 
    {% endif %}
{% endblock %}

carpool/rides/templates/rides/request.html
{% extends "rides/base.html" %}
{% block title %} Request Ride {% endblock %}
{% block content %}
{% if message %}
<div>
    {message}}
</div>
{% endif %}

<form action="{% url 'rides:request_ride' %}" method="POST">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="origin">From</label>
        <input type="text" class="form-control" name="origin" placeholder="Sitapaila" required>
      </div>
      <div class="form-group col-md-6">
        <label for="destination">To</label>
        <input type="text" class="form-control" name="destination" placeholder="Devghat" required>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="Date">Date</label>
        <input type="date" class="form-control" name="date" id="date" required>
      </div>
      <div class="form-group col-md-6">
        <label for="time">Time</label>
        <input type="text" class="form-control" name="timeConstraints" placeholder="When do you need it?" required>
    </div>
    </div>
    <button type="submit" class="btn btn-primary">Request</button>
  </form>
{% endblock %}

{% block account %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
{% endblock %}

carpool/rides/templates/rides/request_detail.html
{% extends 'rides/base.html' %}
{% block title %} {{ ride.id }} {% endblock %}
{% block content %}
    <h3>Details - RSLCB{{ride.id}}</h3>
    <div class="table-container">
    <table class="table table-hover mt-3">
        <tr>
            <th>Origin</th>
            <th>Destination</th>
            <th>Date</th>
            <th>Time</th>
            <th>Requested by</th>
        </tr>
        <tr>
            <td>{{ride.origin}}</td>
            <td>{{ride.destination}}</td>
            <td>{{ride.date}}</td>
            <td>{{ride.time}}</td>
            <td>{{ride.name.username}}</td>
        </tr>
    </table>
    </div>
    {% if user != ride.name %}
    <p>If you're willing to give this ride, please fill this form.</p>
    <form action="{% url 'rides:request_detail' ride.id %}" method="POST">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6">
              <label for="time">Time</label>
              <input type="time" class="form-control" name="time" value="13:15" required>
            </div>
            <div class="form-group col-md-6">
                <label for="seats">Seats</label>
                <input type="number" class="form-control" name="seats" value="1" required>
              </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="pickupDirections">Pickup Point</label>
                <input type="text" class="form-control" name="pickupDirections" placeholder="Pashupatinath North Door" required>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Give Ride</button>
    </form>
    {% else %}
    <div>You will be sent an email after your ride is accepted.
        <br>
        If you have already gotten another ride, you may cancel your ride request here.
        <br>
        <br>
        <form action="{% url 'rides:request_cancel' ride.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Cancel my request</button>
        </form>
    </div>
    {% endif %}
{% endblock %}
{% block account %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
{% endblock %}

carpool/rides/templates/rides/success.html
{% extends 'rides/base.html' %}
{% block title %} Success {% endblock %}
{% block content %}
{% if host %}
<div>
   New ride created.
</div>
<div>You will shortly be sent an email with additional information</div>
<div>Find this ride <a href="{% url 'rides:detail' ride.id %}">here</a></div>
{% else %}
<h3>Sucess</h3>
<div>{{message}}</div>
{% endif %}
{% endblock %}
{% block account %}
    <li>
        <a href="{% url 'users:my_rides' %}">My Rides</a>
    </li>
    <li>
        <a href="{% url 'users:logout' %}">Logout</a>
    </li>
{% endblock %}